In [1]:
# Label에 결측치가 있는 데이터는 전부 onehot encoding 하였습니다.

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import MinMaxScaler

In [3]:
#dataset 불러오기 
train = pd.read_csv("airline_dataset/train.csv")
test = pd.read_csv("airline_dataset/train.csv")

#dataset 확인
print(train.columns)
train.head()

Index(['id', 'Gender', 'Customer Type', 'Age', 'Type of Travel', 'Class',
       'Flight Distance', 'Seat comfort', 'Departure/Arrival time convenient',
       'Food and drink', 'Gate location', 'Inflight wifi service',
       'Inflight entertainment', 'Online support', 'Ease of Online booking',
       'On-board service', 'Leg room service', 'Baggage handling',
       'Checkin service', 'Cleanliness', 'Online boarding',
       'Departure Delay in Minutes', 'Arrival Delay in Minutes', 'target'],
      dtype='object')

,id,Gender,Customer Type,Age,Type of Travel,Class,Flight Distance,Seat comfort,Departure/Arrival time convenient,Food and drink,...,Ease of Online booking,On-board service,Leg room service,Baggage handling,Checkin service,Cleanliness,Online boarding,Departure Delay in Minutes,Arrival Delay in Minutes,target
0,1,Female,disloyal Customer,22,Business travel,Eco,1599,3,0,3,...,4,5,4,4,4,5,4,0,0.0,0
1,2,Female,Loyal Customer,37,Business travel,Business,2810,2,4,4,...,5,5,4,2,1,5,2,18,18.0,0
2,3,Male,Loyal Customer,46,Business travel,Business,2622,1,1,1,...,4,4,4,4,5,4,3,0,0.0,1
3,4,Female,disloyal Customer,24,Business travel,Eco,2348,3,3,3,...,3,2,4,5,3,4,3,10,2.0,0
4,5,Female,Loyal Customer,58,Business travel,Business,105,3,3,3,...,4,4,4,4,4,4,5,0,0.0,1

In [4]:
# id column 삭제
train.drop('id',axis=1,inplace =True)
test.drop('id',axis=1, inplace =True)


# Gender one_hot encoding
train = pd.get_dummies(train,drop_first=True,columns = ['Gender',
                                                         'Customer Type',
                                                         'Type of Travel',
                                                         'Class',
                                                         'Seat comfort',
                                                         'Food and drink',
                                                         'Inflight entertainment',
                                                         'Leg room service',
                                                         'Online boarding',
                                                         'Ease of Online booking',
                                                         'Inflight wifi service'])

test = pd.get_dummies(test,drop_first=True,columns = ['Gender',
                                                        'Customer Type',
                                                        'Type of Travel',
                                                        'Class',
                                                        'Seat comfort',
                                                        'Food and drink',
                                                        'Inflight entertainment',
                                                        'Leg room service',
                                                        'Online boarding',
                                                        'Ease of Online booking',
                                                        'Inflight wifi service'])


# Departure/Arrival time convenient 삭제 무응답 경우의 수가 많고 target과의 상관관계도 매우 낮음)

train.drop('Departure/Arrival time convenient',axis = 1,inplace = True)
test.drop('Departure/Arrival time convenient',axis = 1,inplace = True)

# Departure Delay in Minutes, Arrival Delay in Minutes, log transform

train['Departure Delay in Minutes'] = np.log1p(train['Departure Delay in Minutes'])
test['Departure Delay in Minutes'] = np.log1p(test['Departure Delay in Minutes'])

train['Arrival Delay in Minutes'] = np.log1p(train['Arrival Delay in Minutes'])
test['Arrival Delay in Minutes'] = np.log1p(test['Arrival Delay in Minutes'])

In [20]:
train

,Age,Flight Distance,Gate location,Online support,On-board service,Baggage handling,Checkin service,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes,...,Ease of Online booking_1,Ease of Online booking_2,Ease of Online booking_3,Ease of Online booking_4,Ease of Online booking_5,Inflight wifi service_1,Inflight wifi service_2,Inflight wifi service_3,Inflight wifi service_4,Inflight wifi service_5
0,22,1599,3,4,5,4,4,5,0.000000,0.000000,...,0,0,0,1,0,0,0,0,1,0
1,37,2810,4,3,5,2,1,5,2.944439,2.944439,...,0,0,0,0,1,1,0,0,0,0
2,46,2622,1,5,4,4,5,4,0.000000,0.000000,...,0,0,0,1,0,0,0,0,1,0
3,24,2348,3,3,2,5,3,4,2.397895,1.098612,...,0,0,1,0,0,0,0,1,0,0
4,58,105,3,5,4,4,4,4,0.000000,0.000000,...,0,0,0,1,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,30,2377,1,4,3,3,4,2,5.356586,5.420535,...,1,0,0,0,0,1,0,0,0,0
2996,24,1643,4,5,2,4,1,3,3.044522,2.639057,...,0,0,0,0,1,0,0,0,0,1
2997,22,1442,3,4,3,3,4,3,4.174387,4.219508,...,0,0,0,1,0,0,0,0,1,0
2998,33,2158,5,4,5,5,5,5,0.000000,1.386294,...,0,0,0,1,0,0,0,0,1,0
2999,42,624,2,4,1,1,3,1,3.367296,1.945910,...,1,0,0,0,0,0,0,1,0,0

In [21]:
test

,Age,Flight Distance,Gate location,Online support,On-board service,Baggage handling,Checkin service,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes,...,Ease of Online booking_1,Ease of Online booking_2,Ease of Online booking_3,Ease of Online booking_4,Ease of Online booking_5,Inflight wifi service_1,Inflight wifi service_2,Inflight wifi service_3,Inflight wifi service_4,Inflight wifi service_5
0,22,1599,3,4,5,4,4,5,0.000000,0.000000,...,0,0,0,1,0,0,0,0,1,0
1,37,2810,4,3,5,2,1,5,2.944439,2.944439,...,0,0,0,0,1,1,0,0,0,0
2,46,2622,1,5,4,4,5,4,0.000000,0.000000,...,0,0,0,1,0,0,0,0,1,0
3,24,2348,3,3,2,5,3,4,2.397895,1.098612,...,0,0,1,0,0,0,0,1,0,0
4,58,105,3,5,4,4,4,4,0.000000,0.000000,...,0,0,0,1,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,30,2377,1,4,3,3,4,2,5.356586,5.420535,...,1,0,0,0,0,1,0,0,0,0
2996,24,1643,4,5,2,4,1,3,3.044522,2.639057,...,0,0,0,0,1,0,0,0,0,1
2997,22,1442,3,4,3,3,4,3,4.174387,4.219508,...,0,0,0,1,0,0,0,0,1,0
2998,33,2158,5,4,5,5,5,5,0.000000,1.386294,...,0,0,0,1,0,0,0,0,1,0
2999,42,624,2,4,1,1,3,1,3.367296,1.945910,...,1,0,0,0,0,0,0,1,0,0

In [ ]:
#PCA