In [1]:
# Label에 결측치가 있는 데이터는 전부 onehot encoding 하였습니다.

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import MinMaxScaler

In [28]:
#dataset 불러오기 
train = pd.read_csv("airline_dataset/train.csv")
test = pd.read_csv("airline_dataset/test.csv")

#dataset 확인
print(train.columns)
train.head()

Index(['id', 'Gender', 'Customer Type', 'Age', 'Type of Travel', 'Class',
       'Flight Distance', 'Seat comfort', 'Departure/Arrival time convenient',
       'Food and drink', 'Gate location', 'Inflight wifi service',
       'Inflight entertainment', 'Online support', 'Ease of Online booking',
       'On-board service', 'Leg room service', 'Baggage handling',
       'Checkin service', 'Cleanliness', 'Online boarding',
       'Departure Delay in Minutes', 'Arrival Delay in Minutes', 'target'],
      dtype='object')

,id,Gender,Customer Type,Age,Type of Travel,Class,Flight Distance,Seat comfort,Departure/Arrival time convenient,Food and drink,...,Ease of Online booking,On-board service,Leg room service,Baggage handling,Checkin service,Cleanliness,Online boarding,Departure Delay in Minutes,Arrival Delay in Minutes,target
0,1,Female,disloyal Customer,22,Business travel,Eco,1599,3,0,3,...,4,5,4,4,4,5,4,0,0.0,0
1,2,Female,Loyal Customer,37,Business travel,Business,2810,2,4,4,...,5,5,4,2,1,5,2,18,18.0,0
2,3,Male,Loyal Customer,46,Business travel,Business,2622,1,1,1,...,4,4,4,4,5,4,3,0,0.0,1
3,4,Female,disloyal Customer,24,Business travel,Eco,2348,3,3,3,...,3,2,4,5,3,4,3,10,2.0,0
4,5,Female,Loyal Customer,58,Business travel,Business,105,3,3,3,...,4,4,4,4,4,4,5,0,0.0,1

In [29]:
train['Ease of Online booking'].unique()

array([4, 5, 3, 1, 2, 0], dtype=int64)

In [30]:
# id column 삭제
train.drop('id',axis=1,inplace =True)
test.drop('id',axis=1, inplace =True)


# Gender one_hot encoding
train = pd.get_dummies(train,drop_first=True,columns = ['Gender',
                                                         'Customer Type',
                                                         'Type of Travel',
                                                         'Class',
                                                         'Seat comfort',
                                                         'Food and drink',
                                                         'Inflight entertainment',
                                                         'Leg room service',
                                                         'Online boarding',
                                                         'Ease of Online booking',
                                                         'Inflight wifi service'])

test = pd.get_dummies(test,drop_first=True,columns = ['Gender',
                                                        'Customer Type',
                                                        'Type of Travel',
                                                        'Class',
                                                        'Seat comfort',
                                                        'Food and drink',
                                                        'Inflight entertainment',
                                                        'Leg room service'])


# Label 0 데이터가 train에만 존재하기 때문에 drop_first = False를 주고 Label 1 데이터를 살려 columns 수와 순서 일치시킴

test = pd.get_dummies(test,drop_first=False,columns = [ 'Online boarding',
                                                        'Ease of Online booking'])

test = pd.get_dummies(test,drop_first=True,columns = ['Inflight wifi service'])

# Departure/Arrival time convenient 삭제 무응답 경우의 수가 많고 target과의 상관관계도 매우 낮음)

train.drop('Departure/Arrival time convenient',axis = 1,inplace = True)
test.drop('Departure/Arrival time convenient',axis = 1,inplace = True)

# Departure Delay in Minutes, Arrival Delay in Minutes, log transform

train['Departure Delay in Minutes'] = np.log1p(train['Departure Delay in Minutes'])
test['Departure Delay in Minutes'] = np.log1p(test['Departure Delay in Minutes'])

train['Arrival Delay in Minutes'] = np.log1p(train['Arrival Delay in Minutes'])
test['Arrival Delay in Minutes'] = np.log1p(test['Arrival Delay in Minutes'])

In [31]:
# column이 하나 더 많은것은 target data 때문임

train.shape

(3000, 51)

In [32]:
test.shape

(2000, 50)

In [33]:
X_train = train.drop('target',axis=1)
y_train = train['target']

In [34]:
#MinMaxscaler

In [35]:
scaler = MinMaxScaler()
scaler.fit(X_train)
scaler.partial_fit(test)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [36]:
X_train = pd.DataFrame(scaler.transform(X_train),columns = X_train.columns)
test = pd.DataFrame(scaler.transform(test), columns = test.columns)

In [42]:
X_train

,Age,Flight Distance,Gate location,Online support,On-board service,Baggage handling,Checkin service,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes,...,Ease of Online booking_1,Ease of Online booking_2,Ease of Online booking_3,Ease of Online booking_4,Ease of Online booking_5,Inflight wifi service_1,Inflight wifi service_2,Inflight wifi service_3,Inflight wifi service_4,Inflight wifi service_5
0,0.192308,0.226727,0.50,0.75,1.00,0.75,0.75,1.00,0.000000,0.000000,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
1,0.384615,0.403981,0.75,0.50,1.00,0.25,0.00,1.00,0.418893,0.419585,...,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0
2,0.500000,0.376464,0.00,1.00,0.75,0.75,1.00,0.75,0.000000,0.000000,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
3,0.217949,0.336358,0.50,0.50,0.25,1.00,0.50,0.75,0.341139,0.156553,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
4,0.653846,0.008050,0.50,1.00,0.75,0.75,0.75,0.75,0.000000,0.000000,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,0.294872,0.340603,0.00,0.75,0.50,0.50,0.75,0.25,0.762060,0.772430,...,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
2996,0.217949,0.233167,0.75,1.00,0.25,0.75,0.00,0.50,0.433132,0.376068,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
2997,0.192308,0.203747,0.50,0.75,0.50,0.50,0.75,0.50,0.593873,0.601283,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
2998,0.333333,0.308548,1.00,0.75,1.00,1.00,1.00,1.00,0.000000,0.197548,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
2999,0.448718,0.084016,0.25,0.75,0.00,0.00,0.50,0.00,0.479052,0.277294,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0

In [43]:
test

,Age,Flight Distance,Gate location,Online support,On-board service,Baggage handling,Checkin service,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes,...,Ease of Online booking_1,Ease of Online booking_2,Ease of Online booking_3,Ease of Online booking_4,Ease of Online booking_5,Inflight wifi service_1,Inflight wifi service_2,Inflight wifi service_3,Inflight wifi service_4,Inflight wifi service_5
0,0.692308,0.290837,0.00,1.00,1.00,1.00,0.50,1.00,0.562128,0.581052,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
1,0.256410,0.262881,0.75,0.00,0.50,1.00,0.75,0.75,0.000000,0.000000,...,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
2,0.576923,0.230094,0.75,0.75,1.00,1.00,0.75,1.00,0.000000,0.000000,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
3,0.602564,0.509953,0.75,1.00,0.25,0.25,1.00,0.25,0.000000,0.000000,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4,0.435897,0.207992,0.50,0.75,0.50,0.25,1.00,0.75,0.000000,0.000000,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,0.705128,0.000585,0.00,0.75,0.50,0.50,0.50,0.50,0.000000,0.000000,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1996,0.333333,0.276200,0.75,1.00,1.00,1.00,0.00,1.00,0.649351,0.656240,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
1997,0.282051,0.343677,0.75,0.50,0.00,0.50,0.75,0.25,0.000000,0.197548,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
1998,0.564103,0.052108,0.75,0.50,0.25,0.25,0.25,0.25,0.636973,0.631395,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1999,0.500000,0.056499,1.00,0.00,0.75,0.75,1.00,0.75,0.000000,0.000000,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0